version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE

dockers:
  - image_templates:
    - &amd_image 'ghcr.io/lemana-tech/tern:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
    - "--push"
    - "--platform=linux/amd64"
    goarch: amd64
    extra_files:
      - go.mod
      - go.sum
      - copy_dir.go
      - main.go
      - ssh_tunnel.go
      - migrate

  - image_templates:
    - &arm_image 'ghcr.io/lemana-tech/tern:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
    - "--push"
    - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - go.mod
      - go.sum
      - copy_dir.go
      - main.go
      - ssh_tunnel.go
      - migrate

docker_manifests:
  - name_template: 'ghcr.io/lemana-tech/tern:{{ .Tag }}'
    image_templates:
      - *amd_image
      - *arm_image

  - name_template: 'ghcr.io/lemana-tech/tern:latest'
    image_templates:
      - *amd_image
      - *arm_image